#!/usr/bin/env python
#coding:utf-8
#Author Zhang Shijie
#买手机
import  socket
ip_port=("127.0.0.1",9999)
#开机
s=socket.socket()
#买手机卡
s.bind(ip_port)
#开机
s.listen(5)
#等待电话，conn是客户端与服务器的连接链路信息
conn,addr=s.accept()
#接受消息
while  1:
    try:
        recv_data=conn.recv(1024)
        if str(recv_data,encoding="utf8") == "exit":
            break
        if len(recv_data) == 0:
            break
        print(recv_data,"resv_data")
        #发消息
        send_data=recv_data.upper()
        print(bytes(send_data).decode("utf8"),"send_data")
        conn.send(send_data)
    except Exception:
        break
#挂电话
conn.close()



#!/usr/bin/env python
#coding:utf-8
#Author Zhang Shijie

import  socket
ip_port=("127.0.0.1",9999)

s=socket.socket()

s.connect(ip_port)
while 1:
    send_data=input(">>>:").strip()
    if len(send_data) == 0:
        continue
    print(send_data,"send_data")
    s.send(bytes(send_data,encoding="utf8"))
    if send_data == "exit":
        break
s.close()